export const points = [
    { title: `appearance`, value: 5 },
    { title: `punctuality`, value: 10 },
    { title: `good behaviour`, value: 5 },
    { title: `no bunking`, value: 10 },
    { title: `positive comment`, value: 5 },
    { title: `school spirit`, value: 30 },
    { title: `school service`, value: 30 },
    { title: `english assessments`, value: 20 },
    { title: `afrikaans assessments`, value: 20 },
    { title: `LO assessments`, value: 20 },
    { title: `HL above 40%`, value: 20 },
    { title: `FAL above 30%`, value: 20 },
    { title: `LO above 40%`, value: 20 },
  ];